"""Add order field to Phase model

Revision ID: 08d64fe80a4a
Revises: 9dea2a476815
Create Date: 2025-03-26 20:05:24.456998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d64fe80a4a'
down_revision = '9dea2a476815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phase', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
